name: Build and SonarCloud Analysis

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master, main ]

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Prepare dependencies
        shell: pwsh
        run: |
          mkdir lib

          # Download and extract JavaFX
          curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/8u202/openjfx-8u202-windows-x64.zip
          Expand-Archive -Path javafx.zip -DestinationPath .
          $sdk = Get-ChildItem -Directory -Filter "javafx-sdk*" | Select-Object -First 1
          if ($sdk) {
            Rename-Item -Path $sdk.FullName -NewName "javafx-sdk"
            Copy-Item "javafx-sdk\jre\lib\ext\*" lib\ -Force -ErrorAction SilentlyContinue
          }

          # Download JFoenix
          curl -L https://repo1.maven.org/maven2/com/jfoenix/jfoenix/8.0.10/jfoenix-8.0.10.jar -o lib/jfoenix-8.0.10.jar

          # Copy all existing JARs from repo into lib
          Get-ChildItem -Path . -Recurse -Include *.jar | ForEach-Object { Copy-Item $_.FullName lib\ -Force }

      - name: Compile Java sources
        shell: pwsh
        run: |
          mkdir out
          $files = Get-ChildItem -Recurse -Include *.java src | ForEach-Object { $_.FullName }
          javac -cp ".;lib/*" -d out $files

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
