on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master, main ]

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Prepare dependencies
        shell: pwsh
        run: |
          mkdir lib

          # Download and extract JavaFX
          Invoke-WebRequest -Uri https://download2.gluonhq.com/openjfx/8u202/openjfx-8u202-windows-x64.zip -OutFile javafx.zip
          Expand-Archive -Path javafx.zip -DestinationPath .
          $dir = Get-ChildItem -Directory | Where-Object { $_.Name -like "javafx-sdk*" } | Select-Object -First 1
          Rename-Item -Path $dir.FullName -NewName "javafx-sdk"
          Copy-Item -Path "javafx-sdk\jre\lib\ext\*" -Destination "lib" -Recurse -Force -ErrorAction SilentlyContinue

          # Download JFoenix
          Invoke-WebRequest -Uri https://repo1.maven.org/maven2/com/jfoenix/jfoenix/8.0.10/jfoenix-8.0.10.jar -OutFile lib/jfoenix-8.0.10.jar

      - name: Compile Java sources
        shell: pwsh
        run: |
          mkdir out
          $files = Get-ChildItem -Recurse -Include *.java src | ForEach-Object { $_.FullName }
          javac -cp ".;lib/*" -d out $files

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
