name: Build and SonarCloud Analysis

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master, main ]

jobs:
  sonarqube:
    name: SonarCloud Analysis
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Prepare dependencies
        run: |
          mkdir lib
          curl -L https://download2.gluonhq.com/openjfx/8u202/openjfx-8u202-windows-x64.zip -o javafx.zip
          tar -xf javafx.zip
          cp -r javafx-sdk*/jre/lib/ext/* lib/ || true

          curl -L https://repo1.maven.org/maven2/com/jfoenix/jfoenix/8.0.10/jfoenix-8.0.10.jar -o lib/jfoenix-8.0.10.jar

      - name: Compile Java sources
        run: |
          mkdir out
          javac -cp ".;lib/*" -d out $(Get-ChildItem -Recurse -Include *.java src)

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
